import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { Mock } from 'vitest'
import {
  REALTIME_ALIAS,
  renderLegacyOverride,
  renderOverride,
} from '@/lib/engine/override'
import {
  declaredContainerNames,
  declaredProjectName,
  resolveLegacyProjectName,
} from '@/lib/engine/layout'

// Mock the docker module for resolveTarget tests
vi.mock('@/lib/engine/run', () => ({
  docker: vi.fn(),
}))

// Mock fs for resolveTarget tests (layout.ts uses `import { promises as fs } from 'fs'`)
vi.mock('fs', () => ({
  promises: {
    readFile: vi.fn(),
    writeFile: vi.fn(),
    access: vi.fn(),
  },
}))

const { docker } = await import('@/lib/engine/run')
const { promises: fsPromises } = await import('fs')
const mockedDocker = docker as Mock
const mockedReadFile = fsPromises.readFile as Mock
const mockedAccess = fsPromises.access as Mock

// `docker compose -f docker-compose.yml config --services` for upstream
// self-hosted/v0.8.2.
const UPSTREAM_SERVICES = [
  'db', 'imgproxy', 'meta', 'studio', 'api-gw', 'auth', 'functions',
  'realtime', 'rest', 'storage', 'supavisor',
]

// Splits rendered override text into { service: [its indented lines] }.
function blocks(yaml: string): Record<string, string[]> {
  const out: Record<string, string[]> = {}
  let current: string | null = null
  for (const line of yaml.split('\n')) {
    const service = line.match(/^ {2}([a-z0-9._-]+):$/)
    if (service) {
      current = service[1]
      out[current] = []
    } else if (current && line.startsWith('    ')) {
      out[current].push(line.trim())
    }
  }
  return out
}

const ALIAS_LINES = ['networks:', 'default:', 'aliases:', `- "${REALTIME_ALIAS}"`]

describe('renderOverride: persistent profile', () => {
  const yaml = renderOverride({ profile: 'persistent', services: UPSTREAM_SERVICES })
  const b = blocks(yaml)

  it('covers every upstream service and resets each fixed container_name', () => {
    expect(Object.keys(b).sort()).toEqual([...UPSTREAM_SERVICES].sort())
    for (const service of UPSTREAM_SERVICES) {
      expect(b[service][0]).toBe('container_name: !reset null')
    }
  })

  it('adds the realtime alias Envoy targets', () => {
    expect(b.realtime).toEqual(['container_name: !reset null', ...ALIAS_LINES])
  })

  it('keeps the full service set and ports as published today', () => {
    expect(yaml).not.toMatch(/profiles:/)
    expect(yaml).not.toMatch(/ports:/)
    expect(yaml).not.toMatch(/depends_on:/)
    for (const service of UPSTREAM_SERVICES.filter((s) => s !== 'realtime')) {
      expect(b[service]).toEqual(['container_name: !reset null'])
    }
  })

  it('matches the snapshot', () => {
    expect(yaml).toMatchInlineSnapshot(`
      "# Generated by SupaConsole. Do not edit: it is rewritten on every deploy.
      # Applied as: docker compose -p <project> -f docker-compose.yml -f supaconsole.override.yml
      # Profile: persistent

      services:
        db:
          container_name: !reset null
        imgproxy:
          container_name: !reset null
        meta:
          container_name: !reset null
        studio:
          container_name: !reset null
        api-gw:
          container_name: !reset null
        auth:
          container_name: !reset null
        functions:
          container_name: !reset null
        realtime:
          container_name: !reset null
          networks:
            default:
              aliases:
                - "realtime-dev.supabase-realtime"
        rest:
          container_name: !reset null
        storage:
          container_name: !reset null
        supavisor:
          container_name: !reset null
      "
    `)
  })
})

describe('renderOverride: preview profile (T5 spec)', () => {
  const b = blocks(renderOverride({ profile: 'preview', services: UPSTREAM_SERVICES }))

  it('drops studio, meta and supavisor via profiles, clearing the pooler ports', () => {
    expect(b.studio).toEqual(['profiles: ["omitted"]'])
    expect(b.meta).toEqual(['profiles: ["omitted"]'])
    expect(b.supavisor).toEqual(['profiles: ["omitted"]', 'ports: !reset []'])
  })

  it('publishes the gateway on loopback only, without the studio dependency', () => {
    expect(b['api-gw']).toEqual([
      'container_name: !reset null',
      'depends_on: !reset {}',
      'ports: !override',
      '- "127.0.0.1:${API_GW_HTTP_PORT}:8000/tcp"',
    ])
  })

  it('keeps the realtime alias', () => {
    expect(b.realtime).toEqual(['container_name: !reset null', ...ALIAS_LINES])
  })

  it('resets container_name on the kept client-facing services only', () => {
    for (const service of ['db', 'auth', 'rest', 'storage', 'imgproxy', 'functions']) {
      expect(b[service]).toEqual(['container_name: !reset null'])
    }
    for (const service of ['studio', 'meta', 'supavisor']) {
      expect(b[service]).not.toContain('container_name: !reset null')
    }
  })
})

describe('renderLegacyOverride', () => {
  it('adds only the realtime alias, leaving container names alone', () => {
    const yaml = renderLegacyOverride(UPSTREAM_SERVICES)
    expect(blocks(yaml)).toEqual({ realtime: ALIAS_LINES })
    expect(yaml).not.toMatch(/container_name/)
  })

  it('renders an empty override when the release has no realtime service', () => {
    expect(renderLegacyOverride(['db', 'rest'])).toMatch(/^services: \{\}$/m)
  })
})

describe('service list validation', () => {
  it('rejects names that are not compose service names', () => {
    expect(() => renderOverride({ profile: 'persistent', services: ['db', 'evil:\n  x'] })).toThrow(/Invalid compose service name/)
    expect(() => renderOverride({ profile: 'persistent', services: ['-p'] })).toThrow(/Invalid compose service name/)
  })

  it('rejects an empty list and collapses duplicates', () => {
    expect(() => renderOverride({ profile: 'persistent', services: [] })).toThrow(/no services/)
    const b = blocks(renderOverride({ profile: 'persistent', services: ['db', 'db'] }))
    expect(Object.keys(b)).toEqual(['db'])
  })
})

describe('legacy compose scanning', () => {
  const legacy = [
    '# Usage',
    'name: demo-1791431330128',
    '',
    'services:',
    '  studio:',
    '    container_name: demo-1791431330128-studio',
    '  realtime:',
    '    # comment',
    '    container_name: "realtime-dev.demo-1791431330128-supabase-realtime"',
  ].join('\n')

  it('reads the top-level name and the rewritten container names', () => {
    expect(declaredProjectName(legacy)).toBe('demo-1791431330128')
    expect(declaredContainerNames(legacy)).toEqual([
      'demo-1791431330128-studio',
      'realtime-dev.demo-1791431330128-supabase-realtime',
    ])
    expect(declaredProjectName('services:\n  db:\n    image: x\n')).toBeNull()
  })
})

describe('resolveLegacyProjectName', () => {
  const dockerDir = '/srv/sc/supabase-projects/demo-1/docker'
  const base = {
    slug: 'demo-1',
    dockerDir,
    declaredName: 'demo-1-declared',
    declaredContainerNames: ['demo-1-db', 'demo-1-auth'],
  }

  it('prefers the project label on containers compose created from this directory', () => {
    const result = resolveLegacyProjectName({
      ...base,
      containers: [
        { name: 'renamed-db', project: 'original-project', workingDir: dockerDir },
        { name: 'demo-1-auth', project: 'something-else', workingDir: '/elsewhere' },
        { name: 'unrelated', project: 'other', workingDir: '/srv/other' },
      ],
    })
    expect(result).toEqual({ projectName: 'original-project', source: 'containers' })
  })

  it('falls back to the label on containers with the declared names', () => {
    const result = resolveLegacyProjectName({
      ...base,
      containers: [
        { name: 'demo-1-db', project: 'moved-project', workingDir: '/old/path/docker' },
        { name: 'unrelated', project: 'other', workingDir: '/srv/other' },
      ],
    })
    expect(result).toEqual({ projectName: 'moved-project', source: 'containers' })
  })

  it('refuses to guess when the project containers disagree', () => {
    expect(() =>
      resolveLegacyProjectName({
        ...base,
        containers: [
          { name: 'demo-1-db', project: 'a', workingDir: dockerDir },
          { name: 'demo-1-auth', project: 'b', workingDir: dockerDir },
        ],
      })
    ).toThrow(/more than one compose project/)
  })

  it("uses the compose file's top-level name when nothing is running", () => {
    expect(resolveLegacyProjectName({ ...base, containers: [] })).toEqual({
      projectName: 'demo-1-declared',
      source: 'compose-name',
    })
  })

  it('falls back to the slug last', () => {
    expect(resolveLegacyProjectName({ ...base, declaredName: null, containers: [] })).toEqual({
      projectName: 'demo-1',
      source: 'slug',
    })
    expect(resolveLegacyProjectName({ ...base, declaredName: 'Not Valid', containers: [] }).source).toBe('slug')
  })
})

describe('resolveTarget', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: no override marker file exists (legacy project), compose file has no name
    mockedReadFile.mockImplementation((path: string) => {
      if (path.includes('.supaconsole-project.json')) {
        return Promise.reject(new Error('ENOENT'))
      }
      if (path.includes('docker-compose.yml')) {
        return Promise.resolve('services: {}\n')
      }
      return Promise.reject(new Error('ENOENT'))
    })
    mockedAccess.mockResolvedValue(undefined)
  })

  it('resolves leading-dash slug via compose config when no containers', async () => {
    // Compose file has invalid name (leading dash), no containers running
    mockedReadFile.mockImplementation((path: string) => {
      if (path.includes('.supaconsole-project.json')) {
        return Promise.reject(new Error('ENOENT'))
      }
      if (path.includes('docker-compose.yml')) {
        return Promise.resolve('name: -demo-123\nservices: {}\n')
      }
      return Promise.reject(new Error('ENOENT'))
    })
    mockedDocker
      .mockResolvedValueOnce({ stdout: '' }) // listContainerLabels returns empty
      .mockResolvedValueOnce({
        stdout: JSON.stringify({
          name: 'demo-123',
          services: {},
          networks: {},
          volumes: {},
        }),
      }) // resolveNameFromComposeConfig
    const { resolveTarget } = await import('@/lib/engine/layout')
    const dockerDir = '/srv/sc/supabase-projects/-demo-123/docker'
    const result = await resolveTarget(dockerDir, '-demo-123')
    expect(result.projectName).toBe('demo-123')
    expect(mockedDocker).toHaveBeenCalledTimes(2)
    expect(mockedDocker).toHaveBeenNthCalledWith(
      2,
      ['compose', '-f', 'docker-compose.yml', 'config', '--format', 'json'],
      { cwd: dockerDir, timeout: 60000 }
    )
  })

  it('does not invoke docker compose config when slug is already valid', async () => {
    // Compose file has no name, slug is valid
    mockedReadFile.mockImplementation((path: string) => {
      if (path.includes('.supaconsole-project.json')) {
        return Promise.reject(new Error('ENOENT'))
      }
      if (path.includes('docker-compose.yml')) {
        return Promise.resolve('services: {}\n')
      }
      return Promise.reject(new Error('ENOENT'))
    })
    mockedDocker.mockResolvedValue({ stdout: '' }) // listContainerLabels returns empty
    const { resolveTarget } = await import('@/lib/engine/layout')
    const validDockerDir = '/srv/sc/supabase-projects/valid-project/docker'
    const result = await resolveTarget(validDockerDir, 'valid-project')
    expect(result.projectName).toBe('valid-project')
    // docker should only be called for listContainerLabels, not for config
    expect(mockedDocker).toHaveBeenCalledTimes(1)
    expect(mockedDocker).toHaveBeenCalledWith(
      ['ps', '-a', '--no-trunc', '--format', '{{.Names}}\t{{.Label "com.docker.compose.project"}}\t{{.Label "com.docker.compose.project.working_dir"}}'],
      { timeout: 60000 }
    )
  })
})
