// Generates the compose override SupaConsole layers on top of an unmodified
// upstream docker-compose.yml, replacing the old regex rewrite of
// container_name. Pure: the service list is passed in (at runtime it comes
// from `docker compose config --services`), so this is unit-testable.
//
// Profiles:
//   persistent - projects created from the UI: every upstream service, ports
//                published as the upstream file declares them, compose-derived
//                container names (`<project>-<service>-1`) and the realtime alias.
//   preview    - the trimmed, loopback-only stack from the T5 spike: studio,
//                meta and supavisor dropped via profiles, the gateway on
//                127.0.0.1 only with no studio dependency, and the alias.
//
// Legacy projects (compose file already rewritten with per-project
// container_names) get only the realtime alias; see renderLegacyOverride.

export type OverrideProfile = 'persistent' | 'preview'

export const OVERRIDE_FILE = 'supaconsole.override.yml'

// Envoy's realtime cluster (volumes/api/envoy/cds.yaml) targets this hostname,
// and realtime derives its tenant id from it. Upstream gets it for free from
// its fixed container_name; once the name is per-project it must be an alias
// on the stack's own network, or the websocket gets 503 "no healthy upstream".
export const REALTIME_SERVICE = 'realtime'
export const REALTIME_ALIAS = 'realtime-dev.supabase-realtime'

export const GATEWAY_SERVICE = 'api-gw'
export const PREVIEW_OMITTED_SERVICES = ['studio', 'meta', 'supavisor'] as const

const SERVICE_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/

export interface RenderOverrideInput {
  profile: OverrideProfile
  services: string[]
}

function checkServices(services: string[]): string[] {
  const seen = new Set<string>()
  for (const name of services) {
    if (!SERVICE_NAME_RE.test(name)) {
      throw new Error(`Invalid compose service name: ${JSON.stringify(name)}`)
    }
    seen.add(name)
  }
  if (seen.size === 0) throw new Error('Cannot render an override for a compose file with no services')
  return [...seen]
}

function realtimeNetworks(): string[] {
  return [
    '    networks:',
    '      default:',
    '        aliases:',
    `          - ${JSON.stringify(REALTIME_ALIAS)}`,
  ]
}

const HEADER = [
  '# Generated by SupaConsole. Do not edit: it is rewritten on every deploy.',
  '# Applied as: docker compose -p <project> -f docker-compose.yml -f ' + OVERRIDE_FILE,
]

export function renderOverride({ profile, services }: RenderOverrideInput): string {
  const names = checkServices(services)
  const lines = [...HEADER, `# Profile: ${profile}`, '', 'services:']
  const omitted = new Set<string>(profile === 'preview' ? PREVIEW_OMITTED_SERVICES : [])

  for (const name of names) {
    lines.push(`  ${name}:`)
    if (omitted.has(name)) {
      // Never started unless the "omitted" profile is enabled. The pooler's
      // host ports are cleared too, so nothing else is published.
      lines.push('    profiles: ["omitted"]')
      if (name === 'supavisor') lines.push('    ports: !reset []')
      continue
    }
    lines.push('    container_name: !reset null')
    if (profile === 'preview' && name === GATEWAY_SERVICE) {
      lines.push('    depends_on: !reset {}')
      lines.push('    ports: !override')
      lines.push('      - "127.0.0.1:${API_GW_HTTP_PORT}:8000/tcp"')
    }
    if (name === REALTIME_SERVICE) lines.push(...realtimeNetworks())
  }
  return lines.join('\n') + '\n'
}

// Legacy projects keep their rewritten compose file and container names; the
// override adds only the realtime alias (Gate 1 finding A).
export function renderLegacyOverride(services: string[]): string {
  const names = checkServices(services)
  const lines = [...HEADER, '# Profile: legacy (rewritten compose file, container names kept)', '']
  if (!names.includes(REALTIME_SERVICE)) {
    lines.push('services: {}')
    return lines.join('\n') + '\n'
  }
  lines.push('services:', `  ${REALTIME_SERVICE}:`, ...realtimeNetworks())
  return lines.join('\n') + '\n'
}
